### ISSUE TITLE
Hassio support

### ISSUE THREAD

**Issue by gregoryduckworth** [dmitrif/onvif2mqtt#1]
Hi, 

Great work on this! Just wanted to know if it would be possible to get the ability to add it to Hassio directly using the https://www.home-assistant.io/hassio/installing_third_party_addons/ method?

Thanks!

**Comment by dmitrif** [comment]
Hi, @gregoryduckworth!
I will take a look to see the effort level.

**Comment by dmitrif** [comment]
Hi, it seems like the HASS add-on wrapping would require HASS specific instrumentation which seems to be out of scope for this utility. If desired, feel free to submit a PR and I will take a look.
