### ISSUE TITLE
bell button

### ISSUE THREAD

**Issue by jacobhallgren** [dmitrif/onvif2mqtt#11]
Can you implement event for when the ring button is pressed?

**Comment by privatesam** [comment]
I second this.  If you can get the button push then this is a gamechanger.

**Comment by juan11perez** [comment]
Yes for bell button

**Comment by dmitrif** [comment]
Hi all! Which devices are you using? In the case of EzViz DB1 and other analogues, they do not publish the bell button event unfortunately.

**Comment by dmitrif** [comment]
Closing as stale.
