### ISSUE TITLE
Multiple devices?

### ISSUE THREAD

**Issue by dmelgar** [dmitrif/onvif2mqtt#12]
I have two ONVIF devices including an EZVIZ doorbell camera.

What does the config file look like for multiple devices? Is it supported?
I tried two sections starting with `-name`. 
That seemed to result in duplicate events generated when the first device detected motion.

FYI: I tested with an Amcrest 4mp and Amcrest 8mp POE camera. They both appear to work fine.
I also tested with a Reolink 5mp POE camera. It did not work with that camera.

**Comment by dmitrif** [comment]
Hi! Let me double check the config parsing. It should be an array notation as you tried.

**Comment by geiseri** [comment]
I see the same with two different ONVIF cameras.  If the first one fires, they both fire.  If the second one fires it is ignored.

**Comment by gjohansson-ST** [comment]
Same here. They fire in pair. Any workaround by someone?

**Comment by dmelgar** [comment]
Not a great workaround. I have followed the code to see where the issue may be. 
I cloned the repo in two different directories with two different configurations and ran each on separately. That works but doesn't scale. I now have 6 cameras I'd like to monitor.

**Comment by gjohansson-ST** [comment]
> Not a great workaround. I have not followed the code to see where the issue may be.
> I cloned the repo in two different directories with two different configurations and ran each on separately. That works but doesn't scale. I now have 6 cameras I'd like to monitor.

Yes. I just setup two docker containers for now and run the two separately. Ok for two cameras but I am getting my third shortly so it's getting out of hand a bit. Hope this can be resolved.
Not a js fan so I won't look at the code for this one.

**Comment by gjohansson-ST** [comment]
There is no work on this?
It works perfectly but it's a bit disturbing to have one container per camera.

**Comment by dmitrif** [comment]
Hi, been focusing on a few other projects. There is support for this but seems like a bug is biting this functionality. I will take a look at addressing this one :)

**Comment by ksupipr** [comment]
This ONVIF lib bug. 
https://github.com/agsh/onvif/commit/db11f201648abd92fbe0147f1143ffcf6d044104?branch=db11f201648abd92fbe0147f1143ffcf6d044104&diff=split

Update onvif on last version and can use multiple devices

**Comment by dmitrif** [comment]
Resolved on latest. Please reopen if issue persists
