### ISSUE TITLE
mqtts connection yaml parameters

### ISSUE THREAD

**Issue by dmitryos** [dmitrif/onvif2mqtt#18]
Hi mate,
Is it possible to provide connection parameters for mqtts connection? Could not t it working with different option from MQTT.js doc.

Thank you,
Dmitry

**Comment by dmitrif** [comment]
Hi, @dmitryos 
Does this not work?
```
# MQTT Broker configuration, 
# required due to nature of project.
mqtt:
  host: 192.168.0.57
  port: 1883
  username: user
  password: password

```

What other options are you looking for? We could make this passthrough to the client.
