### ISSUE TITLE
Dynamic loading of changes of config.yml

### ISSUE THREAD

**Issue by TerehinAV** [dmitrif/onvif2mqtt#2]
Hi!
Great job! This is what I was looking for a very long time.
Is it possible to add config.yml monitoring?
The task is to dynamically add/remove camera's subscriptions without restarting container
Thanks!

**Comment by dmitrif** [comment]
Hi! 

What is the usecase here? It adds a bit of complexity to the config fetching + bootstrapping the app, and I want to avoid it if a restart is good enough.

**Comment by TerehinAV** [comment]
This is necessary if the service keeps track of a large number of cameras (which are dynamically added to the configuration) and when motion events are important. In this case, restarting the container may result in the loss of some events.

**Comment by dmitrif** [comment]
Resolved on latest. Please reopen if issue persists
