### ISSUE TITLE
Onvif2mqtt on RPi2 docker

### ISSUE THREAD

**Issue by peteeee** [dmitrif/onvif2mqtt#3]
Hello dmitrif,

Got it working fine on my Intel CPU based HA device.  When I configure the plugin in Docker on a RPi getting an error relating to running the docker instance in Arm.  

Do you have an RPi version of the plugin that I could try?  Trying this remotely on a IPCam Talk forum users set up.

Pete

**Comment by brilthor** [comment]
Not sure if this will be helpful in the meantime, however you could take the dockerfile https://github.com/dmitrif/onvif2mqtt/blob/master/Dockerfile and rebuild it on the raspberry pi to test with in the interim.

**Comment by peteeee** [comment]
Thank you brilthor.

I have never rebuilt a docker file to work on the RPi.

How do I go about that?

**Comment by brilthor** [comment]
it looks like the docker image this dockerfile is based on has arm versions:

![image](https://user-images.githubusercontent.com/567144/81632671-de4c9000-93d8-11ea-8acb-77e49ad25664.png)


As such I think you would just check this repository out on the raspberry pi and point your docker-compose file to this directory or if you're working with a bare image run the appropriate `docker build` command

**Comment by dmitrif** [comment]
Hi, unfortunately I have no plans to currently add docker compilations for any other os targets. If someone is willing, please submit a PR revising to a multi-pronged Docker build and I will merge / review the PR.

**Comment by jsiedentop** [comment]
Building multi arch images is actually not a big deal and is well described in the [documentary](https://docs.docker.com/desktop/multi-arch/).

This should do all the work: 
```
docker buildx create --name mybuilder --use
docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t username/demo:latest --push .
```

I found no github workflow in this repo for the docker build/push, so I was not able to do a pull request. But if you are looking for inspiration on how to create a workflow for this task, I can recommend [this blog post](https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/).
