### ISSUE TITLE
PullPointSubscription request freezes camera (Reolink E1 Zoom)

### ISSUE THREAD

**Issue by new-kirte** [dmitrif/onvif2mqtt#44]
Every 5 seconds I am getting the following in the log and the camera becomes unresponsive:

{"level":50,"time":1621437546824,"name":"ONVIF/camera_reolink_living_room","hostname":"192.168.x.y","msg":"CreatePullPointSubscription camera_reolink_living_room","v":1}

**Comment by ksupipr** [comment]
This camera support ONVIF? port, login, pass is correct?
Lib support Real Time Pull Point Notification Interface only. 

From onvif documentation:

Event handling covers the test cases for the verification of the Event service as mentioned in [ONVIF
Network Interface Specs] and [ONVIF Event WSDL].
The event handling test cases cover the following mandatory interfaces:
• **Basic Notification Interface**
• **Real Time Pull Point Notification Interface**
• **Seek**

**Comment by new-kirte** [comment]
@ksupipr, yes, the camera supports onvif. I updated the firmware and except couple of occasions everything works pretty well
