### ISSUE TITLE
only one of multiple cameras remains active (upstream issue)

### ISSUE THREAD

**Issue by brilthor** [dmitrif/onvif2mqtt#7]
After the initial poll cycle only 1 camera continues to be polled by the onvif cam objects.  There is an upstream pull request to fix this.  Once that pull request is accepted the dependency here needs to be updated to include the new version

https://github.com/agsh/onvif/pull/137

**Comment by dmitrif** [comment]
Waiting on https://github.com/agsh/onvif/pull/161 , let me know if. you'd rather we continue with https://github.com/agsh/onvif/pull/137 as it's now merged.

**Comment by brilthor** [comment]
go ahead and wait for the clean solution; I'm running a locally patched version for the moment

**Comment by dmitrif** [comment]
#21 Should resolve this once merged.

**Comment by dmitrif** [comment]
Resolved on latest. Please reopen if issue persists
