### ISSUE TITLE
Wont run on docker from a synology NAS

### ISSUE THREAD

**Issue by madhits** [dmitrif/onvif2mqtt#8]
sudo docker run -v /opt/config:/config dfarkov/onvif2mqtt

> onvif-cam@1.0.4 start /
> node dist/index.js

{"level":30,"time":1589486125412,"msg":"Loading configuration. {\"configPath\":\"/config/config.yml\"}","v":1}
{"level":30,"time":1589486125493,"msg":"Validating configuration file.","v":1}
{"level":30,"time":1589486126244,"name":"Manager","msg":"Beginning initialization...","v":1}
{"level":30,"time":1589486126245,"name":"MQTT","hostname":"127.0.0.1:1883","msg":"Connecting.","v":1}

I get this output which starts on the docker and I can see it with docker ps command but it never shows up mqtt explorer and I believe it either is not loading the config or it has some prereq that is not met but it is not giving any output to explain whats going on. I have installed the node.js v8 on the synology so that should be all it needs.

**Comment by dmitrif** [comment]
Works on Docker + Synology DS418+ here. It seems like it is unable to connect to MQTT, any further logs from your broker side?

**Comment by dmitrif** [comment]
Closing as stale. Feel free to reopen.
