### ISSUE TITLE
ezviz db1 button press

### ISSUE THREAD

**Issue by clickilan** [dmitrif/onvif2mqtt#9]
is there a way to convey the ezviz db1 button press to an mqtt message?

**Comment by bgilmer77** [comment]
Unfortunately (unbelievably??!!) the door bell button is not available as an ONVIF event.  So there is no way to capture that using this application.  If you install a magnetic reed switch near your doorbell magnet, you can use that to trigger any number of small devices that will create an MQTT event.  Check out [this](https://ipcamtalk.com/threads/new-rca-hsdb2a-3mp-doorbell-ip-camera.31601/page-101) link.

**Comment by dmitrif** [comment]
Doorbell presses are unavailable in the vendor's implementation. @bgilmer77 provides a great alternative. Closing due to lack of possible resolution.
